name = ''                           # (1)
while name != 'your name':          # (2)
    print ('Please type your name.')
    name = raw_input()                  # (3)
print('Thank you!')                 # (4)
